### ISSUE TITLE
TODO Count 2/ FIXME Count 15

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-webpack#29]
- [ ] FIXME: additional error handling?
       Commit: (21b3316) Update bundling.
       File:  [lib/index.js:649](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L649)
       David I. Lehn commented a year ago

  - [ ] FIXME: add new option to control this output
       Commit: (344b709) Enable `--webpack-stats` output.
       File:  [lib/index.js:596](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L596)
       David I. Lehn commented a year ago

  - [ ] FIXME: log/save important parts of stats/info
       Commit: (4436f4c) Add stats and profile options.
       File:  [lib/index.js:595](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L595)
       David I. Lehn commented 3 years ago

  - [ ] FIXME: add support to output the config? (difficult due to plugins and regexes)
       Commit: (21b3316) Update bundling.
       File:  [lib/index.js:560](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L560)
       David I. Lehn commented a year ago

  - [ ] FIXME: add option for symlink control
       Commit: (5634c0a) Fix webpack path processing.
       File:  [lib/index.js:555](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L555)
       David I. Lehn commented 5 months ago

  - [ ] FIXME: remove this when watch support handles symlinks
       Commit: (5634c0a) Fix webpack path processing.
       File:  [lib/index.js:467](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L467)
       David I. Lehn commented 5 months ago

  - [ ] FIXME: these disable polyfills globally
       Commit: (00fb75a) Update for latest bedrock-views changes.
       File:  [lib/index.js:452](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L452)
       David I. Lehn commented a year ago

  - [ ] FIXME: find a better way than hand selecting these
       Commit: (662fdb4) Update babel and polyfill usage.
       File:  [lib/index.js:331](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L331)
       David I. Lehn commented a year ago

  - [ ] FIXME: make default with top-level static import CSS loads
       Commit: (65feda1) Disable mini-css-extract-plugin by default.
       File:  [lib/index.js:266](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L266)
       David I. Lehn commented a year ago

  - [ ] FIXME: always or only when 'isProduction'?
       Commit: (879f2f8) Update CSS extraction loader setup.
       File:  [lib/index.js:265](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L265)
       David I. Lehn commented a year ago

  - [ ] FIXME: are other modes needed?
       Commit: (7f56791) Only define process.env.NODE_ENV in production.
       File:  [lib/index.js:244](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L244)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: are these needed?
       Commit: (7f56791) Only define process.env.NODE_ENV in production.
       File:  [lib/index.js:239](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L239)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: if optimize has specific options, need cli command
       Commit: (d357077) Add initial "watch" support.
       File:  [lib/index.js:189](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L189)
       David I. Lehn commented a year ago

  - [ ] FIXME: improve this
       Commit: (5634c0a) Fix webpack path processing.
       File:  [lib/index.js:144](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L144)
       David I. Lehn commented 5 months ago

  - [ ] FIXME: this should be a param
       Commit: (5634c0a) Fix webpack path processing.
       File:  [lib/index.js:143](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L143)
       David I. Lehn commented 5 months ago

  - [ ] TODO: 'dry' option?
       Commit: (5a7dc6b) Enable clean-webpack-plugin support.
       File:  [lib/index.js:109](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L109)
       David I. Lehn commented 7 months ago

  - [ ] TODO: check to see if we can get `path` from the pseudo package
       Commit: (a9bfef9) Rename `aliases` to `overrideConfigs` and merge full webpack overrides.
       File:  [lib/index.js:705](https://github.com/digitalbazaar/bedrock-webpack/blob/master/lib/index.js#L705)
       Dave Longley commented 2 years ago

FIXME Count         15
       TODO Count          2
       Oldest Comment      3 years ago
       Oldest Commenter    David I. Lehn
       Oldest Comment      FIXME: log/save important parts of stats/info
